#配置端口
server:
  port: 9090
# 配置注册到注册中心的服务名称
spring:
  application:
    name: server-zuul

# 配置服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#自定义路由映射
zuul:
  routes:
    apiwayone:
      path: /api/oneway/**
      serviceId: server-one
    apiwaytwo:
      path: /api/twoway/**
      serviceId: server-two